language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - python setup.py install
  - pip install -e ".[test]"

# command to run tests
script: pytest test
