language: python
# Technically we work on 3.3 as well, but hypothesis doesn't...
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - python setup.py install
  - pip install -e ".[test]"

# command to run tests
script: pytest test
